### ISSUE TITLE
mac address display abnormal on windows 10 and ipv6 address not display.

### ISSUE THREAD

**Issue by JianZhou12345678** [SamuelYvon/netifaces-2#22] opened 2023-12-05 03:55 UTC
I installed netifaces2 on my windows10 64 bit, with python 3.7.6, when i get my network interface("Realtek PCIe GbE Family Controller"), i find mac address show abnormal and not show ipv6 address. I hope netifaces2 can show the same info as old lib netifaces.

![image](https://github.com/SamuelYvon/netifaces-2/assets/61871411/0ae25a26-83f0-451a-a58b-a7c35c04757c)
![image](https://github.com/SamuelYvon/netifaces-2/assets/61871411/0e10a28a-c160-4d7c-a51d-11a7c9fe3a6f)
![image](https://github.com/SamuelYvon/netifaces-2/assets/61871411/bebb9acd-d167-43d7-a9d7-632c42c3cbac)

**Comment by SamuelYvon** [comment] 2023-12-05 14:42
Thanks for reporting! I will be checking this later when I get access to a windows machine. Currently the information is reported by windows tooling, maybe I am parsing it wrong.

**Comment by SamuelYvon** [comment] 2023-12-06 13:40
I was able to reproduce the mac. addr bug. Will look into it. For ipv6, do you have the latest version? Someone else had the same issue.

**Comment by SamuelYvon** [comment] 2023-12-06 14:49
@JianZhou12345678 I fixed the display of the mac addr. in version 0.0.20, which should hit pypi soon. I will investigate for the ivp6 since the windows API seems to be more convoluted to get to the information.

**Comment by SamuelYvon** [comment] 2023-12-17 18:49
Hi @JianZhou12345678 ! Just a little update. I have a PR ready on branch https://github.com/SamuelYvon/netifaces-2/pull/23. I am also testing another fix at the same time, so I won't deploy right away. If you want, you can test right now. It does include Ipv6 information.

**Comment by SamuelYvon** [comment] 2024-01-07 16:42
All fixed on latest :)

**Closed** 2024-01-07 16:42 UTC
Labels: bug, waiting for test, windows
